# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/echo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/echo.proto",
    package="echo",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x15test_proto/echo.proto\x12\x04\x65\x63ho"\x17\n\x04\x45\x63ho\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3',
)


_ECHO = _descriptor.Descriptor(
    name="Echo",
    full_name="echo.Echo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="echo.Echo.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=31,
    serialized_end=54,
)

DESCRIPTOR.message_types_by_name["Echo"] = _ECHO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Echo = _reflection.GeneratedProtocolMessageType(
    "Echo",
    (_message.Message,),
    {
        "DESCRIPTOR": _ECHO,
        "__module__": "proto.echo_pb2"
        # @@protoc_insertion_point(class_scope:echo.Echo)
    },
)
_sym_db.RegisterMessage(Echo)


# @@protoc_insertion_point(module_scope)
